name: Leaked Secrets Scan
on:
  pull_request:
  push:
    branches:
      - develop
      - main
      - "[0-9]+.[0-9]+.x"
  workflow_dispatch:
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@4c04bbbe851403f27d0c60ef85f57ce8cb674dcc
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
