name: Leaked Secrets Scan
on:
  pull_request:
  push:
    branches:
      - main
      - "[0-9]+.[0-9]+.x"
  workflow_dispatch:
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: TruffleHog OSS - PR
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
        if: github.ref_name != 'main' && github.event_name != 'release'
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --debug --only-verified
        if: github.ref_name == 'main' && github.event_name == 'release'
