name: Leaked Secrets Scan
on:
  pull_request:
  push:
    branches:
      - develop
      - main
      - "[0-9]+.[0-9]+.x"
  workflow_dispatch:
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@0932ea224b5f9d4ab7e829989a13fdac7aa0383b
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
