name: Leaked Secrets Scan
on:
  pull_request:
  push:
    branches:
      - develop
      - main
      - "[0-9]+.[0-9]+.x"
  workflow_dispatch:
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@b8724e87e6c7f6785bee707a82172d03e3006efb
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
