name: Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        pyv: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.pyv }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.pyv }}
        cache: 'pip'
        cache-dependency-path: setup.cfg

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install
      run: |
        python -m pip install -e '.[tests]'

    - name: Run tests
      env:
        COVERAGE_FILE: ${{ matrix.pyv }}
      run: pytest -v tests --cov --cov-config=pyproject.toml --cov-report=xml

    - name: Upload coverage report
      uses: codecov/codecov-action@v3.1.1
